// Build NodeJS REST API
// Source: https://dev.to/documatic/build-a-rest-api-with-nodejs-and-express-2g5j
// Generated by BuildBridge

console.log("Starting: Build NodeJS REST API");

// Step 1: Initialize a new NodeJS project
